alias ga='git add'
alias gaa='git add -A'
alias gs='git status -s'
alias gst='git status'
alias gc='git commit'
alias gcm='git commit -m'
alias gcam='git commit -am'
alias gca='git commit --amend -m'
alias gco='git checkout'
alias gcob='git checkout -b'
alias gl='git pull'
alias glo="git pull origin"
alias glr='git pull --rebase'
alias glro='git pull --rebase origin'
alias gp='git push'
alias gpo='git push origin'
alias gpfo='git push --force origin'
alias gd='git diff'
alias gb='git branch'
alias gba='git branch -a'
alias gbd='git branch -d'
alias gr='git reset'
alias grh='git reset --hard'
alias gsh='git stash'
alias gshp='git stash pop'
alias gf='git fetch'
alias gm='git merge'
alias gb='git branch'
alias gbd='git branch -D'
alias gre='git restore'
alias grs='git restore --staged'
alias v='vim'
alias n='nvim'
# Just start tmux automatically
if [ -z "$TMUX" ]; then
  tmux attach-session -t default || tmux new-session -s default
fi